use_frameworks!

platform :ios, '13.0'

target 'LiveStreamService_Example' do
  pod 'LiveStreamService', :path => '../'

  target 'LiveStreamService_Tests' do
    inherit! :search_paths

    
  end
end
